### ISSUE TITLE
failed to start daemon 

### ISSUE THREAD

**Issue by wonkytonky2** [iotaledger/goshimmer#624] opened 2020-07-04 17:48 UTC
## Bug description

Briefly describe the bug.
![image](https://user-images.githubusercontent.com/48189056/86518108-d2a4a500-be2e-11ea-9db8-007205fb8dbe.png)

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: 0.2.1

## Hardware specification

- Operating system: win 10
- RAM: 16
- Number of cores: 8+
- Device type: pc

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. let it run
2. suddenly got this error out of nowhere 

## Expected behaviour
no error 

## Actual behaviour

got error
## Errors

Paste any errors that you see, including logs, errors, or screenshots.

see screenshot above

**Comment by Wollac** [comment] 2020-07-05 15:33
Duplicate of #598

**Closed by Wollac** 2020-07-05 15:33 UTC
Labels: bug
