### ISSUE TITLE
Add eligibility flag to transactions

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1494] opened 2021-06-22 11:41 UTC
Which do not reference via weak parents their dependencies until those get confirmed

**Comment by hmoog** [comment] 2021-06-23 11:36
More detailed description: We only want to pick up messages that contain transactions that either directly reference a message containing the transaction that created its dependencies (outputs) or that spends confirmed outputs.

The reason is that since we got rid of the past cone check we don't want to accidentally confirm a 2nd spend when the 1st spend still has a chance to eventually get orphaned.

**Comment by GalRogozinski** [comment] 2021-06-29 13:07
@hmoog 
why must it *directly* reference the message? If the message is also *indirectly* referenced isn't also fine?
I mean if I am approved all references are approved as well (up to weak references of course)

I initially thought that the reason was that it will be hard to do wall the walks...
But I think I saw utils that use markers todo this efficiently (I just skimmed the code, maybe it isn't so efficient?)

**Comment by daria305** [comment] 2021-06-29 14:24
Test 1 - dependencies have been confirmed 
Test 2 - data msg always eligible 
Test 3 - dependency through the direct message approval gets eligible even if dependency not confirmed
Test 4 - a mix of test 1 and test 3 
Test 5 - some dependency are confirmed and some not, awaits for confirmation of all dependency then eligible
Test 6 - two msgs are dependent on the same transaction that gets confirmed. One msg is eligible because it had no more dependencies, the other is not because it still has some dependency not confirmed

**Comment by hmoog** [comment] 2021-06-30 10:42
> @hmoog
> why must it _directly_ reference the message? If the message is also _indirectly_ referenced isn't also fine?
> I mean if I am approved all references are approved as well (up to weak references of course)
> 
> I initially thought that the reason was that it will be hard to do wall the walks...
> But I think I saw utils that use markers to do this efficiently (I just skimmed the code, maybe it isn't so efficient?)

There is code to do past cone checks with the markers but there are situations when the markers dont give you a definite yes / no but only a maybe s an answer and you will need to walk in these situations.

Even tho the walks didnt happen very often, they could happen from time to time which rendered the node unresponsive for several minutes. This is why we are getting rid of the indirect references.

**Comment by jonastheis** [comment] 2022-03-08 11:36
Closed in favor of #1493

**Closed by jonastheis** 2022-03-08 11:36 UTC
