### ISSUE TITLE
Corrupted db after panic update

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/goshimmer#1344] opened 2021-05-24 21:00 UTC
## Bug description

After updating to the latest Docker version the node crashes a few minutes after getting synced. Looks like the pow is causing the crash, which gives the node a corrupted db.

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: v0.6.2

## Hardware specification

What hardware are you using?

- Operating system:  Arch Linux 64bit / Linux 5.11.16-arch1-1
- RAM: 64 Gb
- Number of cores: Xeon 8 HT
- Device type: Bare metal

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  Update to Goshimmer version v0.6.2 (Docker version), delete current db if corrupted.
2.  Start node, wait to get synced.
3.  Let node do pow (either using a wallet or a drng call)

## Expected behaviour

Pow should function normally.

## Actual behaviour

Pow crashes the node.

## Errors

[goshimmer_crash_after_synced.log](https://github.com/iotaledger/goshimmer/files/6534925/goshimmer_crash_after_synced.log)

**Comment by jonastheis** [comment] 2021-06-08 07:11
This is actually unrelated to the PoW. It was caused by messages scheduled/booked twice which results in the `IndividuallyMappedMessage` being updated. It was fixed with https://github.com/iotaledger/goshimmer/pull/1347

**Closed by jonastheis** 2021-06-08 07:11 UTC
Labels: bug
