### ISSUE TITLE
GoShimmer node on Raspberry Pi3

### ISSUE THREAD

**Issue by StefanoCore** [iotaledger/goshimmer#59] opened 2019-07-28 13:29 UTC
After successful compilation of the GO code, the node crashes as soon as i run it.

![image](https://user-images.githubusercontent.com/10340922/62007324-716b5080-b14c-11e9-86ac-b7ecaffd84d6.png)

![image](https://user-images.githubusercontent.com/10340922/62007263-aa56f580-b14b-11e9-8896-fd83358d4cd0.png)

Here the tech specs of my Raspi:

![image](https://user-images.githubusercontent.com/10340922/62007286-ec803700-b14b-11e9-8c11-e6134ba18cf4.png)

![image](https://user-images.githubusercontent.com/10340922/62007300-24877a00-b14c-11e9-94c2-8c0592af515d.png)

![image](https://user-images.githubusercontent.com/10340922/62007311-48e35680-b14c-11e9-97f7-1b7f5585558c.png)

**Comment by RandirVithren** [comment] 2019-07-28 20:16
I can confirm this mistake:

![sh](https://user-images.githubusercontent.com/53409537/62012331-45b88c80-b185-11e9-9a99-5f93a8cfc07a.png)

Specs of the pi:
![log](https://user-images.githubusercontent.com/53409537/62012335-510bb800-b185-11e9-8807-bb18f39c9eb9.png)

**Comment by b0-ones** [comment] 2019-07-29 08:04
Possible duplicate of https://github.com/iotaledger/goshimmer/issues/49

**Closed** 2020-02-13 12:09 UTC
