### ISSUE TITLE
Automatic snapshotting

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1445] opened 2021-06-14 12:50 UTC
Each day we should make a copy of the current snapshot via the api `/snapshot` so we can bootstrap a new network from a more recent state. This snapshot does not need to be public (aka doesn't need to be available on dbfiles.iota.org). Only keep data around of 1 week.

**Comment by karimodm** [comment] 2021-09-23 08:56
Duplicate of https://github.com/iotaledger/goshimmer/issues/1665

**Closed by karimodm** 2021-09-23 08:56 UTC
Labels: DevOps
