### ISSUE TITLE
ERROR FPC the given branches are conflicting and can not be aggregated

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/goshimmer#596] opened 2020-06-30 20:54 UTC
## GoShimmer version

0.2.0

## Hardware specification

- Operating system: Windows 10
- RAM: 16 GB
- Number of cores: 4
- Device type: Desktop

## Errors

```
ERROR   FPC     valuetransfers/dapp.go:126      the given branches are conflicting and can not be aggregated
github.com/iotaledger/goshimmer/dapps/valuetransfers.configure.func1                                                                                                   
        /__w/goshimmer/goshimmer/dapps/valuetransfers/dapp.go:126                                                                           
github.com/iotaledger/hive.go/events.ErrorCaller                                                                                                                       
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/events/types.go:8                          
github.com/iotaledger/hive.go/events.(*Event).Trigger                                                                                                                  
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/events/event.go:32                         
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).processSolidificationStackEntry                                                         
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:1231                                                        
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).solidifyPayload                                                                         
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:1039                                                        
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).AttachPayloadSync                                                                       
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:118                                                         
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).AttachPayload.func1                                                                     
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:82                                                          
github.com/iotaledger/hive.go/async.(*WorkerPool).Submit.func1                                                                                                         
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/async/workerpool.go:41                     
github.com/panjf2000/ants/v2.(*goWorker).run.func1                                                                                                                     
        /github/home/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.1/worker.go:68                                                                                                                                              
recovered from panic in WorkerPool: update forbidden goroutine 9720611 [running]:                                                                                                                                             
runtime/debug.Stack(0xc00028c8d4, 0xffffffffffffffff, 0x1c2d150)                                                                                                       
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4                                                                                   
github.com/iotaledger/hive.go/async.(*WorkerPool).Submit.func1.1(0xc00028c8c8)                                                                                         
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/async/workerpool.go:37 +0x95                                                                                                 
panic(0x137b0c0, 0x1c2d150)                                                                                                                                            
        /usr/local/go/src/runtime/panic.go:969 +0x174                                                                                       
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*TransactionMetadata).Update(0xc00d35e420, 0x1c89480, 0xc00d343760)                              
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/transactionmetadata.go:397 +0x40                                      
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).updateResult(0xc013b42a80, 0x1c89480, 0xc00d343760)                                                    
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/objectstorage/cached_object.go:162 +0x210  
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).putObjectInCache(0xc000198f80, 0x1c89480, 0xc00d343760, 0x0)                                              
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/objectstorage/object_storage.go:730 +0xb3  
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).Store(0xc000198f80, 0x1c89480, 0xc00d343760, 0x305493d17daefb28, 0x10bc0b43246c8beb)                      
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/objectstorage/object_storage.go:70 +0xb3   
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).storeTransactionModels(0xc00028c870, 0xc0112f8fd0, 0xc014726690, 0xc0147266a0, 0x1, 0x0)
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:992 +0x214                                                  
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).AttachPayloadSync(0xc00028c870, 0xc0112f8fd0)                                           
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:96 +0x12a                                                   
github.com/iotaledger/goshimmer/dapps/valuetransfers/packages/tangle.(*Tangle).AttachPayload.func1()                                                                   
        /__w/goshimmer/goshimmer/dapps/valuetransfers/packages/tangle/tangle.go:82 +0x3a                                                    
github.com/iotaledger/hive.go/async.(*WorkerPool).Submit.func1()                                                                                                       
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200625105326-310ea88f1337/async/workerpool.go:41 +0x5d               
github.com/panjf2000/ants/v2.(*goWorker).run.func1(0xc014a58bd0)                                                                                                       
        /github/home/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.1/worker.go:68 +0x9b                                                                                                                                        
created by github.com/panjf2000/ants/v2.(*goWorker).run                                                                                                                
        /github/home/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.1/worker.go:48 +0x53
```

**Comment by luca-moser** [comment] 2020-06-30 20:56
dupe of #597

**Closed by luca-moser** 2020-06-30 20:56 UTC
Labels: bug
